name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Unit tests
        run: pnpm test:unit
      - name: Accessibility smoke
        run: MHP_A11Y=true pnpm test:a11y
        env:
          CI: true
      - name: Build TypeScript projects
        run: pnpm build
      - name: Validate manifests
        run: pnpm validate:manifests
      - name: Validate inputs config
        run: pnpm validate:inputs
