name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  package-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Package artifacts
        run: pnpm deploy:package
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mhp-release-artifacts
          path: artifacts
